definitions:
  api.errorData:
    properties:
      code:
        type: string
      id:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
  api.repositoryItem:
    properties:
      name:
        type: string
      owner:
        type: string
    type: object
  api.repositoryList:
    properties:
      items:
        items:
          $ref: '#/definitions/api.repositoryItem'
        type: array
      lastPage:
        type: integer
    type: object
info:
  contact: {}
  description: '### Git-based headless CMS API.'
  license:
    name: MIT
    url: https://github.com/moonwalker/moonbase/blob/main/LICENSE
  title: Moonbase API
  version: "1.0"
paths:
  /list:
    get:
      consumes:
      - application/json
      parameters:
      - description: 'page of results to retrieve (default: `1`)'
        in: query
        name: page
        type: string
      - description: 'number of results to include per page (default: `30`)'
        in: query
        name: per_page
        type: string
      - description: 'how to sort the repository list, can be one of `created`, `updated`,
          `pushed`, `full_name` (default: `full_name`)'
        in: query
        name: sort
        type: string
      - description: 'direction in which to sort repositories, can be one of `asc`
          or `desc` (default when using `full_name`: `asc`; otherwise: `desc`)'
        in: query
        name: direction
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.repositoryList'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errorData'
      security:
      - bearerToken: []
      summary: List repositories
      tags:
      - repositories
securityDefinitions:
  bearerToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
