info:
  contact: {}
  description: Git-based headless CMS API.
  license:
    name: MIT
    url: https://github.com/moonwalker/moonbase/blob/main/LICENSE
  title: Moonbase API
paths:
  /login/github:
    get:
      consumes:
      - application/json
      description: github login
      operationId: gh-login
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: login via github
swagger: "2.0"
